### ISSUE TITLE
Plugin breaks v4l2-ctl Zoom Settings

### ISSUE THREAD

**Issue by plasticlobster** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#92] opened 2020-12-10 09:33 UTC
When the plugin is running, it forces the frame of the camera to be zoomed all the way out. Normally I can zoom my camera with something like `v4l2-ctl -c zoom_absolute=500`, but the camera setting doesn't do anything while the spaghetti detective plugin is running.

I also tested the functionality by issuing a command to increase Z during a print, and the printer produced several minutes of intentional spaghetti without being detected, even though I put the sensitivity on the highest setting, but I suspect that's an issue for the other repo (I installed my own server) unless it's just because the camera was so zoomed out it couldn't see the strands.

Either way, being able to continue controlling zoom is critical while using this plugin.

Using Spaghetti Detective plugin version 1.4.5 on Octoprint 1.5.1 on a Raspberry pi 3+ with Logitech c920x Pro webcam

**Comment by kennethjiang** [comment] 2021-01-25 04:27
Sorry for whatever reason I missed this issue.

It is true TSD webcam streaming in "advanced mode" will disable zoom function. You can fall back to [compatibility mode](https://www.thespaghettidetective.com/docs/streaming-compatibility-mode/) at the cost of lower frame rate and higher CPU usage.

I'll close this issue as this is not a bug. But you can still add more comments to this issue if you want to.

**Closed by kennethjiang** 2021-01-25 04:27 UTC
